### ISSUE TITLE
Paper Citations

### ISSUE THREAD

**Issue by manuliner** [belambert/asr-evaluation#20]
Can you name a paper on which this ASR Evaluation is based on?

thank you very much

**Comment by belambert** [comment]
Hi, it's based on standard [edit distance](https://en.wikipedia.org/wiki/Edit_distance) and [word error rate](https://en.wikipedia.org/wiki/Word_error_rate).  I don't know of a good paper to cite, but you could probably cite a good ASR or algorithms textbook.  Does that help?

**Comment by belambert** [comment]
Closing this issue.  Let me know if you need any more help!
