### ISSUE TITLE
issues about calculating WER and WRR using python2.7

### ISSUE THREAD

**Issue by ganji15** [belambert/asr-evaluation#3]
@belambert 
Very useful package, however, there might be a little mistake when calcualtes the WER and WRR if we use python2.7:
I think 'error_count' and 'match_count' should be convert to type 'float' if you use python2.7

asr_evaluation/asr_evaluation.py(line65-66)
-------------
```python
print('WRR: {0:f} % ({1:10d} / {2:10d})'.format(100 * match_count / ref_token_count, match_count, ref_token_count))
print('WER: {0:f} % ({1:10d} / {2:10d})'.format(100 * error_count / ref_token_count, error_count, ref_token_count))
```

Anyway, it's a good package!

**Comment by belambert** [comment]
Thank you and thanks for pointing this out!  I've been using Python3 pretty exclusively lately so I hadn't noticed.  I believe I just fixed the problem.  If you try again and still have the problem please let me know.

**Comment by ganji15** [comment]
@belambert 
It works very well! This package helps me a lot, thank you very much!

**Comment by belambert** [comment]
Excellent, you're very welcome.
